//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACKinshipFormatter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACKinshipFormatter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of $_.
        /// </summary>
        internal static string DEFAULT {
            get {
                return ResourceManager.GetString("DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:ON} great grandchild.
        /// </summary>
        internal static string Kinship__CCC_ {
            get {
                return ResourceManager.GetString("Kinship_#CCC#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:ON} great granddaughter.
        /// </summary>
        internal static string Kinship__CCD_ {
            get {
                return ResourceManager.GetString("Kinship_#CCD#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:ON} great grandson.
        /// </summary>
        internal static string Kinship__CCS_ {
            get {
                return ResourceManager.GetString("Kinship_#CCS#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step {0:ON} great grandchild.
        /// </summary>
        internal static string Kinship__ECCC_ {
            get {
                return ResourceManager.GetString("Kinship_#ECCC#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step {0:ON} great granddaughter.
        /// </summary>
        internal static string Kinship__ECCD_ {
            get {
                return ResourceManager.GetString("Kinship_#ECCD#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step {0:ON} great grandson.
        /// </summary>
        internal static string Kinship__ECCS_ {
            get {
                return ResourceManager.GetString("Kinship_#ECCS#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:ON} great grand niece.
        /// </summary>
        internal static string Kinship__GCCD_C {
            get {
                return ResourceManager.GetString("Kinship_#GCCD#C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:ON} great grand nephew.
        /// </summary>
        internal static string Kinship__GCCS_C {
            get {
                return ResourceManager.GetString("Kinship_#GCCS#C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half {0:ON} great grand niece.
        /// </summary>
        internal static string Kinship__PCCCD_C {
            get {
                return ResourceManager.GetString("Kinship_#PCCCD#C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half {0:ON} great grand nephew.
        /// </summary>
        internal static string Kinship__PCCCS_C {
            get {
                return ResourceManager.GetString("Kinship_#PCCCS#C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step {0:ON} great grand niece.
        /// </summary>
        internal static string Kinship__PECCCD_C {
            get {
                return ResourceManager.GetString("Kinship_#PECCCD#C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step {0:ON} great grand nephew.
        /// </summary>
        internal static string Kinship__PECCCS_C {
            get {
                return ResourceManager.GetString("Kinship_#PECCCS#C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step {0:ON} great grandfather.
        /// </summary>
        internal static string Kinship__PEPF_ {
            get {
                return ResourceManager.GetString("Kinship_#PEPF#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step {0:ON} great grandmother.
        /// </summary>
        internal static string Kinship__PEPM_ {
            get {
                return ResourceManager.GetString("Kinship_#PEPM#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step {0:ON} great grandparent.
        /// </summary>
        internal static string Kinship__PEPP_ {
            get {
                return ResourceManager.GetString("Kinship_#PEPP#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1:ON} cousin.
        /// </summary>
        internal static string Kinship__PGC_ {
            get {
                return ResourceManager.GetString("Kinship_#PGC#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1:ON} cousin {4:CN}x removed.
        /// </summary>
        internal static string Kinship__PGC_C {
            get {
                return ResourceManager.GetString("Kinship_#PGC#C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:ON} great uncle.
        /// </summary>
        internal static string Kinship__PPB_ {
            get {
                return ResourceManager.GetString("Kinship_#PPB#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half {1:ON} cousin.
        /// </summary>
        internal static string Kinship__PPCC_ {
            get {
                return ResourceManager.GetString("Kinship_#PPCC#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half {1:ON} cousin {4:CN}x removed.
        /// </summary>
        internal static string Kinship__PPCC_C {
            get {
                return ResourceManager.GetString("Kinship_#PPCC#C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step {1:ON} cousin.
        /// </summary>
        internal static string Kinship__PPECC_ {
            get {
                return ResourceManager.GetString("Kinship_#PPECC#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step {1:ON} cousin {4:CN}x removed.
        /// </summary>
        internal static string Kinship__PPECC_C {
            get {
                return ResourceManager.GetString("Kinship_#PPECC#C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:ON} great grandfather.
        /// </summary>
        internal static string Kinship__PPF_ {
            get {
                return ResourceManager.GetString("Kinship_#PPF#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:ON} great grandmother.
        /// </summary>
        internal static string Kinship__PPM_ {
            get {
                return ResourceManager.GetString("Kinship_#PPM#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:ON} great grandparent.
        /// </summary>
        internal static string Kinship__PPP_ {
            get {
                return ResourceManager.GetString("Kinship_#PPP#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half {0:ON} great aunt.
        /// </summary>
        internal static string Kinship__PPPD_ {
            get {
                return ResourceManager.GetString("Kinship_#PPPD#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step {0:ON} great aunt.
        /// </summary>
        internal static string Kinship__PPPED_ {
            get {
                return ResourceManager.GetString("Kinship_#PPPED#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step {0:ON} great uncle.
        /// </summary>
        internal static string Kinship__PPPES_ {
            get {
                return ResourceManager.GetString("Kinship_#PPPES#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half {0:ON} great uncle.
        /// </summary>
        internal static string Kinship__PPPS_ {
            get {
                return ResourceManager.GetString("Kinship_#PPPS#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:ON} great aunt.
        /// </summary>
        internal static string Kinship__PPZ_ {
            get {
                return ResourceManager.GetString("Kinship_#PPZ#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brother.
        /// </summary>
        internal static string Kinship_B {
            get {
                return ResourceManager.GetString("Kinship_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to child.
        /// </summary>
        internal static string Kinship_C {
            get {
                return ResourceManager.GetString("Kinship_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grandchild.
        /// </summary>
        internal static string Kinship_CC {
            get {
                return ResourceManager.GetString("Kinship_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to great grandchild.
        /// </summary>
        internal static string Kinship_CCC {
            get {
                return ResourceManager.GetString("Kinship_CCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to great granddaughter.
        /// </summary>
        internal static string Kinship_CCD {
            get {
                return ResourceManager.GetString("Kinship_CCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to great grandson.
        /// </summary>
        internal static string Kinship_CCS {
            get {
                return ResourceManager.GetString("Kinship_CCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to granddaughter.
        /// </summary>
        internal static string Kinship_CD {
            get {
                return ResourceManager.GetString("Kinship_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to son-in-law.
        /// </summary>
        internal static string Kinship_CH {
            get {
                return ResourceManager.GetString("Kinship_CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grandson.
        /// </summary>
        internal static string Kinship_CS {
            get {
                return ResourceManager.GetString("Kinship_CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daughter-in-law.
        /// </summary>
        internal static string Kinship_CW {
            get {
                return ResourceManager.GetString("Kinship_CW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daughter.
        /// </summary>
        internal static string Kinship_D {
            get {
                return ResourceManager.GetString("Kinship_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spouse.
        /// </summary>
        internal static string Kinship_E {
            get {
                return ResourceManager.GetString("Kinship_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brother-in-law.
        /// </summary>
        internal static string Kinship_EB {
            get {
                return ResourceManager.GetString("Kinship_EB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stepchild.
        /// </summary>
        internal static string Kinship_EC {
            get {
                return ResourceManager.GetString("Kinship_EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step grandchild.
        /// </summary>
        internal static string Kinship_ECC {
            get {
                return ResourceManager.GetString("Kinship_ECC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step great grandchild.
        /// </summary>
        internal static string Kinship_ECCC {
            get {
                return ResourceManager.GetString("Kinship_ECCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step great granddaughter.
        /// </summary>
        internal static string Kinship_ECCD {
            get {
                return ResourceManager.GetString("Kinship_ECCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step great grandson.
        /// </summary>
        internal static string Kinship_ECCS {
            get {
                return ResourceManager.GetString("Kinship_ECCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step granddaughter.
        /// </summary>
        internal static string Kinship_ECD {
            get {
                return ResourceManager.GetString("Kinship_ECD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step grandson.
        /// </summary>
        internal static string Kinship_ECS {
            get {
                return ResourceManager.GetString("Kinship_ECS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stepdaughter.
        /// </summary>
        internal static string Kinship_ED {
            get {
                return ResourceManager.GetString("Kinship_ED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to father-in-law.
        /// </summary>
        internal static string Kinship_EF {
            get {
                return ResourceManager.GetString("Kinship_EF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mother-in-law.
        /// </summary>
        internal static string Kinship_EM {
            get {
                return ResourceManager.GetString("Kinship_EM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stepson.
        /// </summary>
        internal static string Kinship_ES {
            get {
                return ResourceManager.GetString("Kinship_ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sister-in-law.
        /// </summary>
        internal static string Kinship_EZ {
            get {
                return ResourceManager.GetString("Kinship_EZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to father.
        /// </summary>
        internal static string Kinship_F {
            get {
                return ResourceManager.GetString("Kinship_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paternal 1st cousin.
        /// </summary>
        internal static string Kinship_FBC {
            get {
                return ResourceManager.GetString("Kinship_FBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paternal 1st cousin.
        /// </summary>
        internal static string Kinship_FBD {
            get {
                return ResourceManager.GetString("Kinship_FBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paternal 1st cousin.
        /// </summary>
        internal static string Kinship_FBS {
            get {
                return ResourceManager.GetString("Kinship_FBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paternal grandfather.
        /// </summary>
        internal static string Kinship_FF {
            get {
                return ResourceManager.GetString("Kinship_FF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paternal 1st cousin.
        /// </summary>
        internal static string Kinship_FGC {
            get {
                return ResourceManager.GetString("Kinship_FGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paternal 1st cousin.
        /// </summary>
        internal static string Kinship_FGD {
            get {
                return ResourceManager.GetString("Kinship_FGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paternal 1st cousin.
        /// </summary>
        internal static string Kinship_FGS {
            get {
                return ResourceManager.GetString("Kinship_FGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paternal grandmother.
        /// </summary>
        internal static string Kinship_FM {
            get {
                return ResourceManager.GetString("Kinship_FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paternal 1st cousin.
        /// </summary>
        internal static string Kinship_FZC {
            get {
                return ResourceManager.GetString("Kinship_FZC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paternal 1st cousin.
        /// </summary>
        internal static string Kinship_FZD {
            get {
                return ResourceManager.GetString("Kinship_FZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paternal 1st cousin.
        /// </summary>
        internal static string Kinship_FZS {
            get {
                return ResourceManager.GetString("Kinship_FZS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sibling.
        /// </summary>
        internal static string Kinship_G {
            get {
                return ResourceManager.GetString("Kinship_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to great grand niece.
        /// </summary>
        internal static string Kinship_GCCD {
            get {
                return ResourceManager.GetString("Kinship_GCCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to great grand nephew.
        /// </summary>
        internal static string Kinship_GCCS {
            get {
                return ResourceManager.GetString("Kinship_GCCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grand niece.
        /// </summary>
        internal static string Kinship_GCD {
            get {
                return ResourceManager.GetString("Kinship_GCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grand nephew.
        /// </summary>
        internal static string Kinship_GCS {
            get {
                return ResourceManager.GetString("Kinship_GCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to niece.
        /// </summary>
        internal static string Kinship_GD {
            get {
                return ResourceManager.GetString("Kinship_GD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brother-in-law.
        /// </summary>
        internal static string Kinship_GH {
            get {
                return ResourceManager.GetString("Kinship_GH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nephew.
        /// </summary>
        internal static string Kinship_GS {
            get {
                return ResourceManager.GetString("Kinship_GS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sister-in-law.
        /// </summary>
        internal static string Kinship_GW {
            get {
                return ResourceManager.GetString("Kinship_GW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to husband.
        /// </summary>
        internal static string Kinship_H {
            get {
                return ResourceManager.GetString("Kinship_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to self.
        /// </summary>
        internal static string Kinship_I {
            get {
                return ResourceManager.GetString("Kinship_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mother.
        /// </summary>
        internal static string Kinship_M {
            get {
                return ResourceManager.GetString("Kinship_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maternal 1st cousin.
        /// </summary>
        internal static string Kinship_MBC {
            get {
                return ResourceManager.GetString("Kinship_MBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maternal 1st cousin.
        /// </summary>
        internal static string Kinship_MBD {
            get {
                return ResourceManager.GetString("Kinship_MBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maternal 1st cousin.
        /// </summary>
        internal static string Kinship_MBS {
            get {
                return ResourceManager.GetString("Kinship_MBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maternal grandfather.
        /// </summary>
        internal static string Kinship_MF {
            get {
                return ResourceManager.GetString("Kinship_MF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maternal 1st cousin.
        /// </summary>
        internal static string Kinship_MGC {
            get {
                return ResourceManager.GetString("Kinship_MGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maternal 1st cousin.
        /// </summary>
        internal static string Kinship_MGD {
            get {
                return ResourceManager.GetString("Kinship_MGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maternal 1st cousin.
        /// </summary>
        internal static string Kinship_MGS {
            get {
                return ResourceManager.GetString("Kinship_MGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maternal grandmother.
        /// </summary>
        internal static string Kinship_MM {
            get {
                return ResourceManager.GetString("Kinship_MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maternal 1st cousin.
        /// </summary>
        internal static string Kinship_MZC {
            get {
                return ResourceManager.GetString("Kinship_MZC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maternal 1st cousin.
        /// </summary>
        internal static string Kinship_MZD {
            get {
                return ResourceManager.GetString("Kinship_MZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maternal 1st cousin.
        /// </summary>
        internal static string Kinship_MZS {
            get {
                return ResourceManager.GetString("Kinship_MZS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parent.
        /// </summary>
        internal static string Kinship_P {
            get {
                return ResourceManager.GetString("Kinship_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1:ON} cousin {4:CN}x removed.
        /// </summary>
        internal static string Kinship_P_PGC_ {
            get {
                return ResourceManager.GetString("Kinship_P#PGC#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half {1:ON} cousin {4:CN}x removed.
        /// </summary>
        internal static string Kinship_P_PPCC_ {
            get {
                return ResourceManager.GetString("Kinship_P#PPCC#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step {1:ON} cousin {4:CN}x removed.
        /// </summary>
        internal static string Kinship_P_PPECC_ {
            get {
                return ResourceManager.GetString("Kinship_P#PPECC#", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uncle.
        /// </summary>
        internal static string Kinship_PB {
            get {
                return ResourceManager.GetString("Kinship_PB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half sibling.
        /// </summary>
        internal static string Kinship_PC {
            get {
                return ResourceManager.GetString("Kinship_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half great grand niece.
        /// </summary>
        internal static string Kinship_PCCCD {
            get {
                return ResourceManager.GetString("Kinship_PCCCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half great grand nephew.
        /// </summary>
        internal static string Kinship_PCCCS {
            get {
                return ResourceManager.GetString("Kinship_PCCCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half grand niece.
        /// </summary>
        internal static string Kinship_PCCD {
            get {
                return ResourceManager.GetString("Kinship_PCCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half grand nephew.
        /// </summary>
        internal static string Kinship_PCCS {
            get {
                return ResourceManager.GetString("Kinship_PCCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half niece.
        /// </summary>
        internal static string Kinship_PCD {
            get {
                return ResourceManager.GetString("Kinship_PCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half nephew.
        /// </summary>
        internal static string Kinship_PCS {
            get {
                return ResourceManager.GetString("Kinship_PCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half sister.
        /// </summary>
        internal static string Kinship_PD {
            get {
                return ResourceManager.GetString("Kinship_PD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stepparent.
        /// </summary>
        internal static string Kinship_PE {
            get {
                return ResourceManager.GetString("Kinship_PE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step uncle.
        /// </summary>
        internal static string Kinship_PEB {
            get {
                return ResourceManager.GetString("Kinship_PEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step sibling.
        /// </summary>
        internal static string Kinship_PEC {
            get {
                return ResourceManager.GetString("Kinship_PEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step great grand niece.
        /// </summary>
        internal static string Kinship_PECCCD {
            get {
                return ResourceManager.GetString("Kinship_PECCCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step great grand nephew.
        /// </summary>
        internal static string Kinship_PECCCS {
            get {
                return ResourceManager.GetString("Kinship_PECCCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step grand niece.
        /// </summary>
        internal static string Kinship_PECCD {
            get {
                return ResourceManager.GetString("Kinship_PECCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step grand nephew.
        /// </summary>
        internal static string Kinship_PECCS {
            get {
                return ResourceManager.GetString("Kinship_PECCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step niece.
        /// </summary>
        internal static string Kinship_PECD {
            get {
                return ResourceManager.GetString("Kinship_PECD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step nephew.
        /// </summary>
        internal static string Kinship_PECS {
            get {
                return ResourceManager.GetString("Kinship_PECS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stepsister.
        /// </summary>
        internal static string Kinship_PED {
            get {
                return ResourceManager.GetString("Kinship_PED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step grandfather.
        /// </summary>
        internal static string Kinship_PEF {
            get {
                return ResourceManager.GetString("Kinship_PEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step grandmother.
        /// </summary>
        internal static string Kinship_PEM {
            get {
                return ResourceManager.GetString("Kinship_PEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step grandparent.
        /// </summary>
        internal static string Kinship_PEP {
            get {
                return ResourceManager.GetString("Kinship_PEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step great grandfather.
        /// </summary>
        internal static string Kinship_PEPF {
            get {
                return ResourceManager.GetString("Kinship_PEPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step great grandmother.
        /// </summary>
        internal static string Kinship_PEPM {
            get {
                return ResourceManager.GetString("Kinship_PEPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step great grandparent.
        /// </summary>
        internal static string Kinship_PEPP {
            get {
                return ResourceManager.GetString("Kinship_PEPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stepbrother.
        /// </summary>
        internal static string Kinship_PES {
            get {
                return ResourceManager.GetString("Kinship_PES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step aunt.
        /// </summary>
        internal static string Kinship_PEZ {
            get {
                return ResourceManager.GetString("Kinship_PEZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grandfather.
        /// </summary>
        internal static string Kinship_PF {
            get {
                return ResourceManager.GetString("Kinship_PF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st cousin.
        /// </summary>
        internal static string Kinship_PGC {
            get {
                return ResourceManager.GetString("Kinship_PGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stepfather.
        /// </summary>
        internal static string Kinship_PH {
            get {
                return ResourceManager.GetString("Kinship_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grandmother.
        /// </summary>
        internal static string Kinship_PM {
            get {
                return ResourceManager.GetString("Kinship_PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grandparent.
        /// </summary>
        internal static string Kinship_PP {
            get {
                return ResourceManager.GetString("Kinship_PP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to great uncle.
        /// </summary>
        internal static string Kinship_PPB {
            get {
                return ResourceManager.GetString("Kinship_PPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half 1st cousin.
        /// </summary>
        internal static string Kinship_PPCC {
            get {
                return ResourceManager.GetString("Kinship_PPCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half aunt.
        /// </summary>
        internal static string Kinship_PPD {
            get {
                return ResourceManager.GetString("Kinship_PPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step grandparent.
        /// </summary>
        internal static string Kinship_PPE {
            get {
                return ResourceManager.GetString("Kinship_PPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step 1st cousin.
        /// </summary>
        internal static string Kinship_PPECC {
            get {
                return ResourceManager.GetString("Kinship_PPECC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step aunt.
        /// </summary>
        internal static string Kinship_PPED {
            get {
                return ResourceManager.GetString("Kinship_PPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step uncle.
        /// </summary>
        internal static string Kinship_PPES {
            get {
                return ResourceManager.GetString("Kinship_PPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to great grandfather.
        /// </summary>
        internal static string Kinship_PPF {
            get {
                return ResourceManager.GetString("Kinship_PPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step grandfather.
        /// </summary>
        internal static string Kinship_PPH {
            get {
                return ResourceManager.GetString("Kinship_PPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to great grandmother.
        /// </summary>
        internal static string Kinship_PPM {
            get {
                return ResourceManager.GetString("Kinship_PPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to great grandparent.
        /// </summary>
        internal static string Kinship_PPP {
            get {
                return ResourceManager.GetString("Kinship_PPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half great aunt.
        /// </summary>
        internal static string Kinship_PPPD {
            get {
                return ResourceManager.GetString("Kinship_PPPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step great aunt.
        /// </summary>
        internal static string Kinship_PPPED {
            get {
                return ResourceManager.GetString("Kinship_PPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step great uncle.
        /// </summary>
        internal static string Kinship_PPPES {
            get {
                return ResourceManager.GetString("Kinship_PPPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half great uncle.
        /// </summary>
        internal static string Kinship_PPPS {
            get {
                return ResourceManager.GetString("Kinship_PPPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half uncle.
        /// </summary>
        internal static string Kinship_PPS {
            get {
                return ResourceManager.GetString("Kinship_PPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step grandmother.
        /// </summary>
        internal static string Kinship_PPW {
            get {
                return ResourceManager.GetString("Kinship_PPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to great aunt.
        /// </summary>
        internal static string Kinship_PPZ {
            get {
                return ResourceManager.GetString("Kinship_PPZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half brother.
        /// </summary>
        internal static string Kinship_PS {
            get {
                return ResourceManager.GetString("Kinship_PS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stepmother.
        /// </summary>
        internal static string Kinship_PW {
            get {
                return ResourceManager.GetString("Kinship_PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aunt.
        /// </summary>
        internal static string Kinship_PZ {
            get {
                return ResourceManager.GetString("Kinship_PZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to son.
        /// </summary>
        internal static string Kinship_S {
            get {
                return ResourceManager.GetString("Kinship_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wife.
        /// </summary>
        internal static string Kinship_W {
            get {
                return ResourceManager.GetString("Kinship_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sister.
        /// </summary>
        internal static string Kinship_Z {
            get {
                return ResourceManager.GetString("Kinship_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PMF]+[GBZ]([CSD])+|EQ(#PGC#);LT(#PGC#C);GT(P#PGC#).
        /// </summary>
        internal static string KinshipRule_1 {
            get {
                return ResourceManager.GetString("KinshipRule_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PMF][EHW]([PMF]){3,}|#PEP$1#.
        /// </summary>
        internal static string KinshipRule_10 {
            get {
                return ResourceManager.GetString("KinshipRule_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ([PMF]){4,}|#PP$1#.
        /// </summary>
        internal static string KinshipRule_11 {
            get {
                return ResourceManager.GetString("KinshipRule_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EHW]([SDC]){4,}|#ECC$1#.
        /// </summary>
        internal static string KinshipRule_12 {
            get {
                return ResourceManager.GetString("KinshipRule_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ([SDC]){4,}|#CC$1#.
        /// </summary>
        internal static string KinshipRule_13 {
            get {
                return ResourceManager.GetString("KinshipRule_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PMF]+[PMF][CSD]([CSD])+|EQ(#PPCC#);LT(#PPCC#C);GT(P#PPCC#).
        /// </summary>
        internal static string KinshipRule_2 {
            get {
                return ResourceManager.GetString("KinshipRule_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PMF]+[PMF][EHW][CSD]([CSD])+|EQ(#PPECC#);LT(#PPECC#C);GT(P#PPECC#).
        /// </summary>
        internal static string KinshipRule_3 {
            get {
                return ResourceManager.GetString("KinshipRule_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PMF]{2,}([BZ])|#PP$1#.
        /// </summary>
        internal static string KinshipRule_4 {
            get {
                return ResourceManager.GetString("KinshipRule_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PMF]{3,}([DS])|#PPP$1#.
        /// </summary>
        internal static string KinshipRule_5 {
            get {
                return ResourceManager.GetString("KinshipRule_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PMF]{3,}[EHW]([DS])|#PPPE$1#.
        /// </summary>
        internal static string KinshipRule_6 {
            get {
                return ResourceManager.GetString("KinshipRule_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BZG]([SDC]){3,}|#GCC$1#C.
        /// </summary>
        internal static string KinshipRule_7 {
            get {
                return ResourceManager.GetString("KinshipRule_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PFM][SDC]([SDC]){3,}|#PCCC$1#C.
        /// </summary>
        internal static string KinshipRule_8 {
            get {
                return ResourceManager.GetString("KinshipRule_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PFM][EHW][SDC]([SDC]){3,}|#PECCC$1#C.
        /// </summary>
        internal static string KinshipRule_9 {
            get {
                return ResourceManager.GetString("KinshipRule_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unrelated.
        /// </summary>
        internal static string KinshipUnrelated {
            get {
                return ResourceManager.GetString("KinshipUnrelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nd.
        /// </summary>
        internal static string Ordinal_ND {
            get {
                return ResourceManager.GetString("Ordinal_ND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rd.
        /// </summary>
        internal static string Ordinal_RD {
            get {
                return ResourceManager.GetString("Ordinal_RD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to st.
        /// </summary>
        internal static string Ordinal_ST {
            get {
                return ResourceManager.GetString("Ordinal_ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th.
        /// </summary>
        internal static string Ordinal_TH {
            get {
                return ResourceManager.GetString("Ordinal_TH", resourceCulture);
            }
        }
    }
}
